

import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/redux/Providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
       <title>Wenchi Jobs</title>
       <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'></link>
       <meta title={metadata.title} description={metadata.description} />
       <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.2.1/moment.min.js"></script>
      </head>   
      <body className={inter.className}>
         <Provider>
          {children}
         </Provider>
      </body>
    </html>
  );
}
